# Generated by Django 3.2.7 on 2021-09-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_authodb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addressDB',
        ),
        migrations.DeleteModel(
            name='authoDB',
        ),
    ]
