# Generated by Django 3.2.7 on 2021-09-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_auto_20210918_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='authoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.IntegerField()),
                ('auth_address', models.CharField(max_length=100)),
            ],
        ),
    ]
